// This file will be auto-generated by `diesel print-schema` after running migrations.
// For now, we define it manually to match our planned database schema.

diesel::table! {
    users (id) {
        id -> Uuid,
        email -> Text,
        created_at -> Timestamptz,
        password_hash -> Nullable<Text>,
    }
}

diesel::table! {
    training_plans (id) {
        id -> Uuid,
        user_id -> Uuid,
        name -> Text,
        description -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    series (id) {
        id -> Uuid,
        plan_id -> Uuid,
        name -> Text,
        order_index -> Int4,
    }
}

diesel::table! {
    exercises (id) {
        id -> Uuid,
        series_id -> Uuid,
        name -> Text,
        muscle_group -> Text,
        sets -> Int4,
        reps_target -> Text,
        rest_seconds -> Int4,
        notes -> Nullable<Text>,
        order_index -> Int4,
    }
}

diesel::table! {
    workout_sessions (id) {
        id -> Uuid,
        user_id -> Uuid,
        series_id -> Nullable<Uuid>,
        started_at -> Timestamptz,
        finished_at -> Nullable<Timestamptz>,
        notes -> Nullable<Text>,
        ai_feedback -> Nullable<Text>,
    }
}

diesel::table! {
    session_logs (id) {
        id -> Uuid,
        session_id -> Uuid,
        exercise_id -> Nullable<Uuid>,
        exercise_name -> Text,
        set_number -> Int4,
        weight_kg -> Nullable<Numeric>,
        reps -> Nullable<Int4>,
        logged_at -> Timestamptz,
    }
}

diesel::table! {
    cardio_logs (id) {
        id -> Uuid,
        user_id -> Uuid,
        activity -> Text,
        duration_min -> Int4,
        distance_km -> Nullable<Numeric>,
        pace_min_km -> Nullable<Numeric>,
        logged_at -> Timestamptz,
        notes -> Nullable<Text>,
    }
}

diesel::table! {
    refresh_tokens (id) {
        id -> Uuid,
        user_id -> Uuid,
        token -> Text,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::joinable!(refresh_tokens -> users (user_id));
diesel::joinable!(training_plans -> users (user_id));
diesel::joinable!(series -> training_plans (plan_id));
diesel::joinable!(exercises -> series (series_id));
diesel::joinable!(workout_sessions -> users (user_id));
diesel::joinable!(session_logs -> workout_sessions (session_id));
diesel::joinable!(cardio_logs -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    refresh_tokens,
    training_plans,
    series,
    exercises,
    workout_sessions,
    session_logs,
    cardio_logs,
);
