ALTER TABLE catalog_exercises ALTER COLUMN user_id DROP NOT NULL;

INSERT INTO catalog_exercises (name, category, exercise_type) VALUES
  ('Supino Reto', 'Peito', 'strength'),
  ('Supino Inclinado', 'Peito', 'strength'),
  ('Supino Declinado', 'Peito', 'strength'),
  ('Crucifixo', 'Peito', 'strength'),
  ('Crossover', 'Peito', 'strength'),
  ('Barra Fixa', 'Costas', 'strength'),
  ('Remada Curvada', 'Costas', 'strength'),
  ('Remada Unilateral', 'Costas', 'strength'),
  ('Puxada Frontal', 'Costas', 'strength'),
  ('Pulldown', 'Costas', 'strength'),
  ('Agachamento Livre', 'Pernas', 'strength'),
  ('Leg Press 45', 'Pernas', 'strength'),
  ('Cadeira Extensora', 'Pernas', 'strength'),
  ('Mesa Flexora', 'Pernas', 'strength'),
  ('Stiff', 'Pernas', 'strength'),
  ('Panturrilha em Pe', 'Pernas', 'strength'),
  ('Desenvolvimento Militar', 'Ombros', 'strength'),
  ('Elevacao Lateral', 'Ombros', 'strength'),
  ('Elevacao Frontal', 'Ombros', 'strength'),
  ('Face Pull', 'Ombros', 'strength'),
  ('Rosca Direta', 'Bracos', 'strength'),
  ('Rosca Martelo', 'Bracos', 'strength'),
  ('Rosca Scott', 'Bracos', 'strength'),
  ('Triceps Pulley', 'Bracos', 'strength'),
  ('Triceps Testa', 'Bracos', 'strength'),
  ('Triceps Frances', 'Bracos', 'strength'),
  ('Corrida', 'Cardio', 'cardio'),
  ('Bicicleta', 'Cardio', 'cardio'),
  ('Caminhada', 'Cardio', 'cardio'),
  ('Natacao', 'Cardio', 'cardio'),
  ('Eliptico', 'Cardio', 'cardio'),
  ('Pular Corda', 'Cardio', 'cardio');
